project:
  title: "sign_languages"
  type: website

format:
  html:
    anchor-sections: false
css: changes.css
from: markdown+emoji
execute:
  freeze: auto

toc: true
toc-location: body
toc-title: "Contents"

mainfont: TTE
monofont: TTE
fontsize: 1.125rem
linkcolor: "#0d6efd"
callout-appearance: simple

reference-location: document
citation-location: document
cap-location: margin

