---
title: "Hawaiʻi Sign Language"
---


## Heads Up {.unnumbered .unlisted}

If you are not me, you should not be here! Assume that everything here is wrong and that I don't know what I'm writing about, cuz I don't.


## What is HSL?

Hawaii Sign Language (HSL), or more properly Hawaiʻi Sign Language, is a dying sign language indigenous to the Hawaiian archipelago. Through the efforts of Linda Yuen Lambrecht and others, it was finally recognized and documented as a natural language in 2013.

One unique aspect of HSL is [its lack of classifiers](http://hdl.handle.net/10125/73260). I think every other sign language in the world has classifiers. I wonder why HSL doesn't have any.


## HSL Info

- [Endangered Language Archive: HSL](https://www.elararchive.org/uncategorized/SO_14be5e56-b629-4d89-9a4e-7a296ce0150e/). By James Woodward and Linda Yuen Lambrecht.
- [A Sketch of Handshape Morphology in Hawai’i Sign Language](http://hdl.handle.net/10125/73260). By Samantha Rarrick. Published 2015.
  + Documents the lack of classifiers in HSL.
- [Ethnologue on HSL](https://www.ethnologue.com/language/hps/).
  + Calls HSL endangered, but also says the HSL has no L1 signers.
- [HAWAII in HSL](https://www.handspeak.com/word/7301/). Video by Crissy Akana Holmes.
  + It looks like HANDSOME or HAWAII, but with the 1-handshape instead of the H-handshape.


## Media

- [LYL's IG](https://www.instagram.com/asltutu/) where she offered a Zoom HSL class.
- [The fight to save Hawaii Sign Language from extinction](https://www.cnn.com/2021/10/08/americas/hawaii-sign-language-extinction-as-equals-intl-cmd/index.html). CNN. Published 2021-10-08.
  + Has a video where multiple HSL signers share their opinions about whether HSL should be saved or not. Big disparity in opinion.
  + Gives one of the lowest number of HSL signers: "But experts estimate that fluent HSL users number in the single digits."