---
title: "Some Notes on ASL"
format: html
css: style_changes.css
from: markdown+emoji
toc: true
toc-location: left
toc-title: "Stuff"
linkcolor: "#000000"
mainfont: FiraGo
monofont: Fira Code
reference-location: margin
citation-location: margin
cap-location: margin
callout-appearance: simple
---

:::{.callout-warning}
## Heads Up

If you are not me, you should not be here! Assume that everything here is wrong and that I don't know what I'm writing about, cuz I don't.
:::

## Intro

I like ASL a lot but I'm not very good at it. I'm hoping that writing this document will help me learn it better.

Originally this was a vocab list---I kept forgetting words. Unfortunately I'm slow and it would take me literal days to transcribe the words and their structure, so I stopped doing that. I also read a bunch of books about ASL and wanted to keep track. And I wanted to be able to easily access the document on multiple devices. So: website!

I make a lot of mistakes and I'm wrong a lot, so hopefully this will help me keep track of those, too.

:::{.callout-note collapse=true}
## Changelog

**2022-10-18**: Added sources and video links.

**2022-10-12**: Finally started putting the site together (as a form of procrastination).

**2022-10-02**: Started `.qmd` document.

**2022-07-17**: The 203rd word was added to the vocab list. Stopped updating after that.

**2022-05-25**: Started `.txt` vocab list!
:::

## Really Cool Things About ASL

1. The 3D structure! Verbal language is 1D + time---it's linear and can only move in one dimension. You can show things in 3D space in ASL which I really like. I'm not great at it but hopefully I'll get better at it.^[[Dragon](https://thatdeafguy.com/2012-10-18/). :dragon:]
2.


## Sources

People I've learned from, books I've read, and resources on ASL and other sign languages.

### Teachers

- Jamil Haque. Levels 1--2. Great teacher! Likes basketball.
- Robert J.^[Doesn't have a bio on the website. Why?] Levels 3--4. Amazing teacher! Likes the wilderness and wolves. Has broken a distressing number of bones.

### Imaginary Teachers

- _American Sign Language: A Teacher's Resource
Text On Grammar and Culture_. By Charlotte Baker and Dennis Cokely. Published 1980.
  + Probably my favorite ASL book so far.
  + From 1980, so it's old. I think most of the stuff is still good. But I'm not qualified to say.
  + I think it was only in 1960 that ASL was recognized as a natural language, so there's a lot of "we don't understand this yet." I wish there were an updated version.
- _Sign-Me-Fine_. By Laura Greene and Eva Barash Dicker. Published 1990.
  + ASL grammar book for kids middle school--age and older.
  + Not very good, unfortunately. Don't think I understand ASL grammar more after reading this.
- The ASL App. By various Deaf signers.
  + This helped me with the numbers. There's lots of other stuff but I haven't use this app for that.

### Dictionaries

- [Handspeak](https://www.handspeak.com/). By Jolanta Lapiak.
  + Great ASL-English dictionary---arguably the best.
  + Has tutorials on grammar and conjunctions and stuff.
- [ASL University](https://www.lifeprint.com/), also known as Lifeprint. By William G. Vicars.
  + ASL-English dictionary with explanations of etymology and suggestions for how to memorize signs. Breaks the handshapes down which I find super useful.
  + Offers an entire ASL curriculum, which is incredible.
  + I think this was one of the first online ASL resources ever. That's really cool.
- _The Gallaudet Dictionary of American Sign Language_. By GU editors and illustrators. Published 2005.
  + Not an exceptional dictionary. Mostly cuz it's so hard to search and pics fail to capture what videos can.
  + Probably best used to remind me what signs look like. But definitely not for learning.
  + The chapter on classifiers is nice, though.
- _The Gallaudet Children‘s Dictionary of American Sign Language_. By GU editors and illustrators. Published 2014.
  + Looks similar to the adult dictionary, but it's more colorful, which I like. :rainbow:
  + Don't have access to it and haven't read it.
  + Has a [companion website](https://gcdasl.com/).

### Linguistics

- _Sign Languages: Structures and Contexts_. By Joseph C. Hill, Diane C. Lillo-Martin and Sandra K. Wood. Published 2019.
  + The first ASL book I read! Turns out that studying linguistics is not the best way to learn a language. 
  + Really good book. Some important things I learned:
    1. Sign languages (like all natural languages) consist of meaningless parts.
    2. There is a specific set of meaningless parts and those parts combine only in certain ways.
    3. In signs that use two hands, either the sign is symmetrical or the non-dominant hand is still. CAT and SALT are respective examples.
- _Linguistics of American Sign Language: An Introduction 3e_. By Clayton Valli and Ceil Lucas. Published 2000.
  + I tried to use this book to learn ASL grammar. Not successful.
  + On the 5th edition (2011) now, but I've only read the 3rd.
  + 5e has a list of [Youtube videos](https://www.youtube.com/playlist?list=PLj06bPbAU0PqBHawkYzQR4AOQO9OInHWO) in lieu of a DVD.
- _Grammar, Gesture, and Meaning in American Sign Language_. By Scott K. Liddell. Published 2003.
  + I haven't read too far into this book. It's a lil beyond my understanding. :sweat_smile:
- [ASL-Lex](https://asl-lex.org/). By Naomi Caselli and others.
  + 2,723 signs are visualized in a network graph. Closeness is correlated with phonological relatedness.^[Phonology is the study of the meaningless parts of a sign.] Node size is correlated with sign frequency.
  + I wonder why phonological relatedness was used and not semantic relatedness, which seems more useful. Like, what's the use with putting "cat" and "bat" next to each other? Or HORNY and HUNGRY?
    - Is it just easier?
    - Their [2017 paper](https://link.springer.com/article/10.3758/s13428-016-0742-0) says the following:  
    "For example, signs like PANTS, DRESS, and SKIRT are all fairly iconic and are produced with relatively common sub-lexical properties: the locations are all on the body (depicting where the clothes are worn), and recruit all four fingers fully extended."
  
### Other Sources

- [Ryan Lepic's ASL Resources](https://sites.google.com/view/ryanlepic/about-me/asl-resources). By Ryan Lepic.
  + Hearing professor at GU.
  + The links to video resources seem helpful.
- [ASL Signbank](https://aslsignbank.haskins.yale.edu/). By Julie A. Hochgesang and many others.
  + A collection of signs organized by glosses for the purpose of annotating ASL videos.
  + Not a learning resource.
- _Sign Languages of the World: A Comparative Handbook_. Edited by Julie Bakken Jepsen, Goedele De Clerck,
Sam Lutalo-Kiingi, and William B. McGregor. Published 2015.
  + An encyclopedia.
  + I've only read the chapter on Inuit Uukturausingit (IUR or Inuit Sign Language).
  + No chapter on Hawaii Sign Language, though it is mentioned.
- [Symbol Font for ASL](https://aslfont.github.io/Symbol-Font-For-ASL/). By Murray Inman.
  + A website with compiled info about writing ASL. Very cool problem that I've never thought about before reading this and going on a hunt for knowledge about written ASL.
  + Seems dead. Hasn't been an update in like a decade.
  + I know Jolanta Lapiak is into written ASL, too.


## Videos to Learn From

### Stories

- [ASL Stories Directory](https://deafchildren.org/knowledge-center/asl-resources/sign-language-stories/).
  + ASL storytime! Stories from primary school books. :book:
- [MyGo! Sign Language for Kids](https://www.youtube.com/channel/UCygtj8VfAI0Sez4S7u65kPg).
  + Kids' shows with ASL interpretation.
- [TreeSchool and Signing Time](https://www.youtube.com/channel/UC2qLnnrBIAdqvbHUiuPmH6w).
  + I think these are songs with accompanied ASL? I don't really get this TBH.
- [Sesame Street ASL songs](https://youtu.be/00xKA_UNEcY) on YouTube.
  + Some Sesame Street songs translated to ASL.
- SignUp, the Chrome extension.
  
### Natural-ish ASL

- [ASL Nook](https://aslnook.com/) and [their YouTube channel](https://www.youtube.com/c/SheenaMcFeely/videos).
  + Natural ASL, mostly by kids. Words in context. Some stories.
- [List of "diverse ASL signers"](https://www.reddit.com/r/asl/comments/xl7y9s/looking_for_diverse_youtube_channels/) on Reddit.
  + Mostly links to YouTube channels.
- [List of videos for receptive practice](https://www.reddit.com/r/asl/comments/vqsqmw/looking_for_youtube_videos_in_asl_not_videos_on/) on Reddit.
  + Again, mostly links to YouTube channels.
  + [OIC Movies](https://www.oicmovies.com/) looks specifically made for receptive practice.

### Just Words

- [Gallaudet University's ASL Connect](https://gallaudet.edu/asl-connect/topics/)
  + Very basic ASL organized by topic.
  + Seems like it's ASL-pic and not ASL-English, which seems significant.


## Mistakes I've Made

So many. I'll try to track them here.

### Overgeneralization

This is a good one, in the sense that kids go through something similar during language acquisition.

When teaching us how to sign race, Jamil signed SOUTH ASIAN for himself. I wrongly assumed the s-handshape was correct for all cardinal directions. Nope. Robert later taught us that north is signed with the n-handshape and so forth.

### Picture Reliance

Sometimes I sign things incorrectly cuz I look at still pics instead of videos. Usually the handshape is right, but I do the movements wrong.


## Notes Notes Notes

Messy messy messy. Very subject to change and full of error.

### Conjunctions

Remember that a conjunction binds two propositions together. ASL has conjunctions similar to English's and even more. In ASL, when signing a conjunction, raise yr eyebrows.

Jolanta Lapiak [has written about conjunctions](https://www.handspeak.com/learn/index.php?id=35).

#### In Class

In Level 4.4 we learned the following conjunctions:

- WRONG: suddenly, without warning
- HAPPEN: just learned, just like that
- DISCOVER: find out, realized
- FRUSTRATED: being stopped from
- HIT: unexpectedly, coincidence

Not sure how to best learn these. I'm worried I'll forget them. And some, like WRONG and HAPPEN, seem kinda similar.

### Receptive Skills

My weak point! Need to practice this a lot lot more than I'm doing now.

- Bill Vicar [has some tips on how to get receptive practice.](https://www.lifeprint.com/asl101/topics/receptive-asl-skills-practice.htm)

### ASL-specific Words

ASL words and concepts that don't easily translate to other languages.

- Rogan Shannon and Ren Putz [talk about ASL slang and exclusive words](https://www.youtube.com/watch?v=K2iRwQJh9dk).
- Bill Vicars [has a list of ASL idioms](https://www.lifeprint.com/asl101/pages-layout/idioms.htm).


## Appendix: HSL

Hawaii Sign Language (HSL), or more properly Hawaiʻi Sign Language, is a dying sign language. It was revealed as a natural language only in 2013.















