---
title: "ASL Resources"
---


## Heads Up {.unnumbered .unlisted}

If you are not me, you should not be here! Assume that everything here is wrong and that I don't know what I'm writing about, cuz I don't.


## What are these Resources About?

These are educational, fun, or interesting resources on ASL, Deaf culture and history, and other sign languages. Sources marked with a :bug: emoji aren't accessible to me, but they're here cuz they seemed useful and maybe I'll look at them one day.

Note to self: remember that the best teacher is a Deaf instructor or tutor. These resources help with learning but are insufficient for getting a thorough understanding of sign languages or Deaf culture.


## Deaf Culture & History

- [Deaf Artists](https://deaf-art.org/). By RIT NTID.
  + Lots of info on Deaf artists and art.
- [Deaf Power](https://deafpower.me/resources/). By Christine Sun Kim and Ravi Vasavan, amongst others.
  + Resources and info from a Deaf power perspective. There is some ASL info, too.
- _Introduction to American Deaf Culture_. First edition. By Thomas K. Holcomb. Published 2012.
  + I like the book a lot. It reads like a mix between a textbook and a casual account.
  + Has a [companion website](http://www.introductiontodeafculture.com/intro-to-deaf-culture.html).
- [Meeting and Interacting with Deaf People](https://www.lifeprint.com/asl101/topics/meeting-deaf-people.htm). By Belinda G. Vicars.
  + How to interact at Deaf events without seeming like a twat.
- _Seeing Language in Sign: The Work of William C. Stokoe_. By Jane Maher. Published 1996.
  + Part Stokoe biography and part narrative history, with a focus on Stokoe's work on ASL linguistics and the negative reception around it.
  + Stokoe talks about learning systems theory in 1957. Way earlier than I thought systems theory originated.
- [Signing Black in America](https://www.talkingblackinamerica.org/signing-black-in-america/). By the Language & Life Project.
  + Documentary about Black ASL.


## Deaf Events

- [Bay Area Asian Deaf Association](https://www.baadaca.com/).
  + Hosts events in the Bay Area.
  + No idea who they are but I liked their 2021 lunar new year video, which can be found on their [Youtube channel](https://www.youtube.com/@baadaca2476).
- [Camp Mark 7](https://www.campmark7.org/).
  + Summer camp for Deaf in very upstate NY.
- [Deaf Coffee](https://deafcoffee.com/).
  + Deaf meetups around the US.
- [Deaf Spotlight](https://www.deafspotlight.org/).
  + Seattle-based arts nonprofit focused on Deaf culture and sign languages.
  + Runs the [Seattle Deaf Film Festival](https://www.deafspotlight.org/sdff).


## Dictionaries

- _American Sign Language Handshape Dictionary_. By Richard A. Tennant and Marianne Gluszak Brown, and drawings by Valerie Nelson-Metlay.
  + Nice reverse dictionary, though kinda outdated. Helped me find INTERNET.
- [ASL Core](https://aslcore.org/). By RIT NTID.
  + Suggested signs for academic + technical topics.
- [ASL University](https://www.lifeprint.com/), also known as Lifeprint. By William G. Vicars.
  + ASL-English dictionary with explanations of etymology and suggestions for how to memorize signs. Breaks the handshapes down which I find super useful.
  + Offers an entire ASL curriculum, which is incredible.
  + I think this was one of the first online ASL resources ever. That's really cool.
- [Handspeak](https://www.handspeak.com/). By Jolanta Lapiak.
  + Great ASL-English dictionary --- arguably the best.
  + Contains an extraordinary reverse dictionary. As far as I can tell, it's the only one online. Some signs in the main dictionary are missing in the reverse dictionary.
  + Has tutorials on grammar and conjunctions and stuff.
- [Signing Savvy](https://www.signingsavvy.com/). By [a large team](https://www.signingsavvy.com/team/leadershipteam).
  + Useful for finding sociolinguistic or phonological variations of different signs.
  + I mostly use this to find signs that I've failed to find elsewhere.
- [Spread the Sign](https://www.spreadthesign.com/en.us/search/). By Thomas Lydell.
  + Translations for multiple sign languages. Pretty neat, though not super comprehensive.
  + They have sentences, too.
- _The Gallaudet Dictionary of American Sign Language_. By GU editors and illustrators. Published 2005.
  + Not an exceptional dictionary. Mostly cuz it's so hard to search and pics fail to capture what videos can.
  + Probably best used to remind me what signs look like. But definitely not for learning.
  + The chapter on classifiers is nice, though.
- _The Gallaudet Children's Dictionary of American Sign Language_. By GU editors and illustrators. Published 2014. :bug:
  + Looks similar to the adult dictionary, but it's more colorful, which I like. :rainbow:
  + Has a [companion website](https://gcdasl.com/).


## Linguistics

### Books

- _Grammar, Gesture, and Meaning in American Sign Language_. By Scott K. Liddell. Published 2003.
  + I haven't read too far into this book. It's a lil beyond my understanding. :sweat_smile:
- _Linguistics of American Sign Language: An Introduction_. Third edition. By Clayton Valli and Ceil Lucas. Published 2000.
  + I tried to use this book to learn ASL grammar. Not successful.
  + On the 5th edition (2011) now, but I've only read the 3rd.
  + 5e has a list of [Youtube videos](https://www.youtube.com/playlist?list=PLj06bPbAU0PqBHawkYzQR4AOQO9OInHWO) in lieu of a DVD.
- _Sign Languages of the World: A Comparative Handbook_. Edited by Julie Bakken Jepsen, Goedele De Clerck, Sam Lutalo-Kiingi, and William B. McGregor. Published 2015.
  + I've only read the chapter on Inuit Uukturausingit (IUR or Inuit Sign Language).
  + No chapter on Hawaii Sign Language, though it is mentioned.
- _Sign Languages: Structures and Contexts_. By Joseph C. Hill, Diane C. Lillo-Martin and Sandra K. Wood. Published 2019.
  + The first ASL book I read! Turns out that studying linguistics is not the best way to learn a language. 
  + Really good book. Some important things I learned:
    1. Sign languages (like all natural languages) consist of meaningless parts.
    2. There is a specific set of meaningless parts and those parts combine only in certain ways.
    3. In signs that use two hands, either the sign is symmetrical or the non-dominant hand is still. CAT and SALT are respective examples.

### Studies

- [ASL-Lex](https://asl-lex.org/). By Naomi Caselli and others.
  + 2,723 signs are visualized in a network graph. Closeness is correlated with phonological relatedness.^[Phonology is the study of the meaningless parts of a word or sign. ] Node size is correlated with sign frequency.
  + It would be nice to also have a graph focused on semantic relatedness. But that's harder.
  + Their [2017 paper](https://link.springer.com/article/10.3758/s13428-016-0742-0) says the following:  
    "For example, signs like PANTS, DRESS, and SKIRT are all fairly iconic and are produced with relatively common sub-lexical properties: the locations are all on the body (depicting where the clothes are worn), and recruit all four fingers fully extended."
- [How the Alphabet Came to Be Used in a Sign Language](https://www.jstor.org/stable/26204903). By Carol Padden and Darline Clark Gunsauls. Published 2003. 
  + Very cool! Mentions that ASL uses a lot of fingerspelling + suggests some reasons why.
  + Most fingerspelled words are nouns.


## ASL Textbooks

- _American Sign Language: A Teacher's Resource Text On Grammar and Culture_. By Charlotte Baker and Dennis Cokely. Published 1980.
  + Probably my favorite ASL book so far.
  + From 1980, so it's old. I think most of the stuff is still good. But I'm not qualified to say.
  + ASL was recognized as a natural language only in 1960, so there's a lot of "we don't understand this yet." I wish there were an updated version.
- _Barron's E-Z American Sign Language_. Third edition. By David Stewart, Elizabeth Stewart, Lisa Dimling, and Jessalyn Little. Published 2011.
  + This is okay. It's teaching me new words. Not sure the grammar stuff is super helpful, though.
- _Sign-Me-Fine_. By Laura Greene and Eva Barash Dicker. Published 1990.
  + ASL grammar book for kids middle school--aged and older.
  + Not very good, unfortunately. Don't think I understand ASL grammar more after reading this.
- [The ASL App](https://theaslapp.com/). By various Deaf signers.
  + Short video lessons on ASL. Mostly vocabulary.
  + This helped me with the numbers beyond 99.


## Storytelling

- [Atlanta Area School for the Deaf Accessible Materials Project](https://www.aasdweb.com/Page/227).
  + Kids' books, family resources, and more.
- [Aunt Alice's ASL TV](https://www.youtube.com/playlist?list=PLyKlPO62EsIltCabT92THlqESi0RVgIwq). By Alice Pascall-Speights.
  + A big YouTube playlist of ASL stories and lessons for kids.
  + My favorite is the ASL interpretation of _Tuesday_. Wow!
- [ASL Educational Resources for Deaf Kids](https://docs.google.com/document/d/1rgAG1vqyU1RAlOZOXSvdyPk0Y4gPN51jOFTqLKN00hw/edit).
  + Google Doc of stories and other educational stuff.
- [ASL Kids Club](https://www.youtube.com/@aslkidsclub).
  + Signing videos and playlists for a wide range of kids' ages.
- [ASL Stories Directory](https://deafchildren.org/knowledge-center/asl-resources/sign-language-stories/).
  + ASL storytime! Stories from primary school books. :book:
- [ASL Storytime by the Washington School for the Deaf](https://www.wsd.wa.gov/video-category/asl-storytime/).
  + Children's stories interpreted in ASL.
- [Charlie Swinbourne's Stories](https://charlieswinbourne.com/). By Charlie Swinbourne.
  + By a Deaf British director depicting Deaf life in the UK. Uses BSL.
  + My current favorite is [Coming Out](https://www.youtube.com/watch?v=K3ai5IVfFdE), which is really funny.
- [Dack Virnig's Stories](https://www.youtube.com/@DackVirnig). By Dack Virnig.
  + Original stories that seem to use a lot of personification.
- [DPAN: Kids Stories in ASL](https://dpan.tv/videos/kids-stories-in-asl/). By DPAN.
  + Kids' stories interpreted in ASL. They seem to specialize in actually showing the physical book while signing, which means images and words can be unclear.
- [Deaf Planet](https://youtube.com/playlist?list=PLuAKHFwj-PlIxxbKDtE15oT7Da9sNuHZq&si=608sZ-yYVMQhKrtY). By a [team of people](https://en.wikipedia.org/wiki/Deafplanet).
  + A TV show consisting of six-minute shorts centered around a hearing boy who lands on a planet full of Deaf people.
- [Keith Wann: Signed Stories](https://keithwann.com/signed-stories)
  + Kids' stories signed by a CODA comedian.
- [Ms. Trina & the ASL Kids Club](https://www.youtube.com/@Ms.TrinaASL). By Ms. Trina.
  + Kids' stories and basic ASL lessons for preschoolers.
- [MyGo! Sign Language for Kids](https://www.youtube.com/channel/UCygtj8VfAI0Sez4S7u65kPg).
  + Kids' shows with ASL interpretation.
- [Pineapple and Cheese](https://www.youtube.com/@PineappleandCheeseASL).
  + Has kids' stories and some vocab in ASL.
- [Silly Paws](https://www.youtube.com/playlist?list=PLPZ40gM7aDFAZt01IovBbI31G1O6cDEb7). Acting by Gaitre Persaud on CDC Kids. Published 2022--23.
  + Twenty-one short toddler-level stories in ASL.
- [Snow White and the Seven Dwarves](https://www.youtube.com/watch?v=bfrnqa2Mlwc).
  + By Eyes Alive and the Florida School for the Deaf and the Blind. Mostly kids signing.
  + Uses [REAL^SICK](https://asl-lex.org/visualization/?sign=real_sick) followed by SICK, which I haven't seen before.^[Around 8:15. ]
- [Sesame Street ASL songs](https://youtu.be/00xKA_UNEcY) on YouTube.
  + Some Sesame Street songs translated to ASL.
  + Joey is a performer for some of them!
- [Signed Stories](https://www.itv.com/signedstories). By ITV.
  + Children's stories signed in ASL or BSL.
- [SignUp](https://www.signupcaptions.com/). By Mariella Satow and ASL interpreters. 
  + Kids' movies interpreted in ASL via a Chrome extension.
  + Unfortunately, the ASL video often isn't well-synchronized with the movie it's meant to be interpreting. This makes it difficult to use.
- [Speak in ASL: Candid Videography](https://www.handspeak.com/learn/251/). By Jolanta Lapiak.
  + Usually, hearing people can safely assume their spoken language is dominant and default. What if a Deaf person flipped the script? What if ASL were the default?
- [TreeSchool and Signing Time](https://www.youtube.com/channel/UC2qLnnrBIAdqvbHUiuPmH6w).
  + I think these are songs with accompanied ASL? I don't really get this TBH.


## ASL in Daily Life

- [ASL Nook](https://aslnook.com/) and [their YouTube channel](https://www.youtube.com/c/SheenaMcFeely/videos).
  + Natural ASL, mostly by kids. Words in context. Some stories.
- [List of "diverse ASL signers"](https://www.reddit.com/r/asl/comments/xl7y9s/looking_for_diverse_youtube_channels/) on Reddit.
  + Mostly links to YouTube channels.
  + [OIC Movies](https://www.oicmovies.com/) looks specifically made for receptive practice, but everything's behind a memberwall.
- [The Daily Moth](https://www.dailymoth.com/).
  + News in ASL, mostly news relevant to the Deaf community.
- [White House YouTube Channel](https://www.youtube.com/@WhiteHouse).
  + Has ASL interpreter.


## Other ASL Pedagogy

### Basics

- [ASL Access](https://www.aslaccess.org/). By the [ASL Access Board](https://www.aslaccess.org/who-we-are).
  + Works to ensure that there are free ASL videos available.
  + Links to [a variety of ASL and English resources](https://www.aslaccess.org/links).
- [ASL Yes](https://www.aslyes.com/). By Garrett Bose.
  + Lots of stuff on grammar and structure, including mouth morphemes. Pretty exciting.
  + Also, there's some vocabulary stuff, too.
- [Gallaudet University's ASL Connect](https://gallaudet.edu/asl-connect/topics/).
  + Very basic ASL organized by topic.
  + It's ASL-pic and not ASL-English.
- [Handspeak: Fingerspelling Receptive Practice](https://www.handspeak.com/learn/413/). By Jolanta Lapiak.
  + As the title. The best fingerspelling reception videos that I've found so far.
- [Lifeprint: Grammar](https://www.lifeprint.com/asl101/pages-layout/grammar.htm). By William G. Vicars.
  + On ASL grammar. See also: [the myth of STORE I GO](https://www.lifeprint.com/asl101/topics/store-i-go-the-myth.htm), his webpage on [ASL sentence structure](https://www.lifeprint.com/asl101/topics/subject-verb-object-asl-sentence-structure.htm), and his page on [repeated movement in ASL](https://www.lifeprint.com/asl101/pages-layout/repeatedmovementofsign.htm).
- [Oklahoma School for the Deaf: ASL Classes](https://courses.osd.k12.ok.us/).
  + Free online classes for ASL 1 and 2. They're asynchronous and consist of videos and written materials.

### Specifics

- [ASL Deafined: Expansion Techniques](https://www.asldeafined.com/2017/12/asl-expansion-techniques/).
  + Seven ASL expansion techniques briefly explained.
- [ASL Rhyme and Rhythmic Songs](https://deafprogressivism.blogspot.com/2013/11/asl-rhyme-and-rhythmic-songs-for-for_16.html). By Barb Wifi.
  + Some notes on ASL rhymes for kids.
- Conjunction info:
  + [Brenda Lyons's ASL Conjunctions Explained](https://www.youtube.com/watch?v=Q8piDMplvwE) has some suggestions for conjunction memorization.
  + [Jolanta Lapiak's Introduction to Conjunctions](https://www.handspeak.com/learn/35/) has a non-exhaustive list of conjunctions and their use.
- [English By Eye, or Read with ASL](https://englishbyeye.org/). By ASL Access.
  + All about education and teaching ASL and English.
  + Their videos focus on teaching signs with multiple meanings.
- _Fingerspelling: Expressive & Receptive Fluency_. By Joyce Linden Groode. Published 2004. :bug:
  + [Website's here](https://www.dawnsign.com/products/details/fingerspelling-expressive-receptive-fluency). The trailer seems very 1990s.
  + Bill Vicars [recommended an older version](https://www.lifeprint.com/asl101/fingerspelling/fingerspellinglexicalized.htm) of this video.
- [RADSCC: ASL Lecture Series](https://www.rit.edu/ntid/radscc-presentations-asl). By RIT NTID.
  + Lectures on ASL and Deaf culture, as well as their histories.
- [Signplaying](https://signplaying.com/home/). By Eric Epstein.
  + Website doesn't seem to work. But it's apparently about creativity in ASL --- wordplay, puns, poetry, that kind of stuff.
  + He presented an [RIT NTID lecture](https://www.youtube.com/watch?v=5j3fSFT45n4) on signplaying.
- [The ASL Lab](https://www.youtube.com/@TheASLLab).
  + Some neat perspectives on ASL use and etymology.

### Vernacular

- [A Deaf Perspective: ASL Signs and Slang](https://www.youtube.com/watch?v=K2iRwQJh9dk). By Rogan Shannon and Ren Putz.
  + Short video on slang and ASL-exclusive words.
- Lists of ASL idioms: [Bill Vicars's](https://www.lifeprint.com/asl101/pages-layout/idioms.htm) and [Jolanta Lapiak's](https://www.handspeak.com/learn/index.php?id=146).


## Miscellaneous Sources

- [ASL Signbank](https://aslsignbank.haskins.yale.edu/). By Julie A. Hochgesang and many others.
  + A collection of signs organized by glosses for the purpose of annotating ASL videos.
  + Not a learning resource.
- [List of ASL Resources](https://docs.google.com/document/d/1nIl25bnKeQl0OXkMZoq9PkW-vC6VFAqlMgBVK4-EsxM/edit). By K.
  + Some resources, though a lot of it isn't useful to me in particular.
- [NAD: Learning American Sign Language](https://www.nad.org/resources/american-sign-language/learning-american-sign-language/). By the NAD.
  + Scattered resources for learning ASL. Also has links to other resources for Deaf.
- [Reddit: List of Videos for Receptive Practice](https://www.reddit.com/r/asl/comments/vqsqmw/looking_for_youtube_videos_in_asl_not_videos_on/).
  + Again, mostly links to YouTube channels.
- [Ryan Lepic's ASL Resources](https://sites.google.com/view/ryanlepic/about-me/asl-resources). By Ryan Lepic.
  + Hearing professor at GU.
  + The links to video resources seem helpful.
- [SignWriting](https://www.signwriting.org/).
  + Sometimes referred to as [Sutton SignWriting](https://en.wikipedia.org/wiki/SignWriting). A 2D writing system for ASL and other sign languages.
  + See the [SignWriting Library](https://www.signwriting.org/library/) for literature, dictionaries, and more.
- [Symbol Font for ASL](https://aslfont.github.io/Symbol-Font-For-ASL/). By Murray Inman.
  + A website with compiled info about writing ASL. Very cool problem that I've never thought about before reading this and going on a hunt for knowledge about written ASL.
  + Seems dead. Hasn't been an update in like a decade.
  + Jolanta Lapiak is into written ASL, too.
